<template>

    <div class="flex h-full flex-col items-center justify-center gap-4">

        <BellAlertIcon class="stroke h-7 w-7 stroke-gray-500" />

        <h3 class="font-semibold">Great! Now, Generate Schedules for your Classes</h3>

        <p class="flex max-w-lg flex-col gap-3 p-8 text-center text-sm text-gray-500">
            <span>
                It's time to generate your class schedules. Our advanced class scheduler is here to assist
                you in creating optimal schedules for your classes.
            </span>

            <span>
                1. The class scheduler utilizes a powerful algorithm that automatically generates schedules based
                on subject priorities and handles overlapping schedules. This means that you can trust the system
                to create the best fit schedule for each class, taking into account various factors to ensure an
                efficient timetable.
            </span>

            <span>
                2. Rest assured that the schedules generated by the system are not set in stone. You will have
                the flexibility to make edits and adjustments later on. If there are any changes required, simply
                access the schedule editing feature to customize it according to your school's needs.
            </span>

            <span>
                3. We understand that time is precious, so generating the schedules will be done seamlessly
                in the background. You can continue exploring and utilizing the system's other features while
                the class schedules are being generated. No need to wait around!
            </span>

            <span>
                4. Once the class schedules are complete, the system will promptly notify you. You will receive
                a notification or an email informing you that the schedules are ready for review. At that point,
                you can access the finalized schedules and proceed with distributing them to teachers and students.
            </span>

        </p>

        <PrimaryButton @click="generateSchedule">Run the Scheduler</PrimaryButton>

    </div>

</template>

<script setup>
import {BellAlertIcon} from "@heroicons/vue/24/outline/index.js";
import PrimaryButton from "@/Components/PrimaryButton.vue";
import {router} from "@inertiajs/vue3";

function generateSchedule() {
    router.post('/batch-schedules/create', {}, {
        onSuccess: () => {
            router.get("/getting-started/school-schedule");
        },
    })
}

</script>

<style scoped>

</style>
