#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
npx lint-staged
./vendor/bin/pint
php artisan cache:clear
php artisan config:clear
php artisan migrate:fresh
./vendor/bin/pest --parallel
php artisan db:seed
